### ISSUE TITLE
Level editor: Being able to toggle blocks whilst you're inside them

### ISSUE THREAD

**Issue by ninjafrostpn** [steppers/revoluzone#1]
You can toggle the red and blue blocks using the spacebar in the level editor whilst the ball is occupying the same grid square as the deactivated block

**Comment by steppers** [comment]
Hi Nijafrostpn,

The editor was very much a WIP and wasn't even complete so don't worry too much about this. It wasn't used at all during the game jam so there are many bugs that can manifest themselves when using it. When time is not so precious I hope to complete it so that it can serve a useful purpose.

Thanks for the heads up! :)
Steppers

**Comment by anton-firmware** [comment]
I can look into it if you want? 

Anton.

**Comment by steppers** [comment]
Go ahead if you want but I think it's a bit messy atm :/

**Comment by steppers** [comment]
Fixed for sliders as well
